apiVersion: v1
kind: Service
metadata:
  name: springpetclinic-k8s

spec:
  ports:
    - nodePort: 30163
      port: 8080
      protocol: TCP
      targetPort: 80
  
  externalIPs:
    - 1.2.4.114
  type: LoadBalancer
  selector:
       app: springpetclinic-k8s
  type: NodePort 